package com.github.sisimomo.graphqlsakila.commons.dao.entity;

import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@MappedSuperclass
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public abstract class BaseUuidAndLongEntity extends BaseUuidEntity implements IBaseLongEntity, IBaseUuidEntity {

  /**
   * Create a column representing the id/primary key of the entity, which will be automatically
   * generated by the database when the entity is persisted for the first. This column cannot be
   * updated and cannot be inserted.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(insertable = false, updatable = false)
  protected Long id;

  /**
   * Generates a hash code base on the primary key.
   *
   * @return The hash code of the object.
   */
  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  /**
   * If the object is the same object, or if the object is null, or if the object is not the same
   * class, then return false. Otherwise, return true if the ids are equal.
   *
   * @param obj The object to compare to.
   * @return a {@code boolean}
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    BaseUuidAndLongEntity other = (BaseUuidAndLongEntity) obj;
    return id != null && other.id != null && Objects.equals(id, other.id);
  }

}
